# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dialogflow/v2beta1/context.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/empty_pb'
require 'google/protobuf/field_mask_pb'
require 'google/protobuf/struct_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.cloud.dialogflow.v2beta1.Context" do
    optional :name, :string, 1
    optional :lifespan_count, :int32, 2
    optional :parameters, :message, 3, "google.protobuf.Struct"
  end
  add_message "google.cloud.dialogflow.v2beta1.ListContextsRequest" do
    optional :parent, :string, 1
    optional :page_size, :int32, 2
    optional :page_token, :string, 3
  end
  add_message "google.cloud.dialogflow.v2beta1.ListContextsResponse" do
    repeated :contexts, :message, 1, "google.cloud.dialogflow.v2beta1.Context"
    optional :next_page_token, :string, 2
  end
  add_message "google.cloud.dialogflow.v2beta1.GetContextRequest" do
    optional :name, :string, 1
  end
  add_message "google.cloud.dialogflow.v2beta1.CreateContextRequest" do
    optional :parent, :string, 1
    optional :context, :message, 2, "google.cloud.dialogflow.v2beta1.Context"
  end
  add_message "google.cloud.dialogflow.v2beta1.UpdateContextRequest" do
    optional :context, :message, 1, "google.cloud.dialogflow.v2beta1.Context"
    optional :update_mask, :message, 2, "google.protobuf.FieldMask"
  end
  add_message "google.cloud.dialogflow.v2beta1.DeleteContextRequest" do
    optional :name, :string, 1
  end
  add_message "google.cloud.dialogflow.v2beta1.DeleteAllContextsRequest" do
    optional :parent, :string, 1
  end
end

module Google
  module Cloud
    module Dialogflow
      module V2beta1
        Context = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.Context").msgclass
        ListContextsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.ListContextsRequest").msgclass
        ListContextsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.ListContextsResponse").msgclass
        GetContextRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.GetContextRequest").msgclass
        CreateContextRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.CreateContextRequest").msgclass
        UpdateContextRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.UpdateContextRequest").msgclass
        DeleteContextRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.DeleteContextRequest").msgclass
        DeleteAllContextsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.DeleteAllContextsRequest").msgclass
      end
    end
  end
end
