# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dialogflow/v2beta1/session.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/cloud/dialogflow/v2beta1/context_pb'
require 'google/cloud/dialogflow/v2beta1/intent_pb'
require 'google/cloud/dialogflow/v2beta1/session_entity_type_pb'
require 'google/protobuf/struct_pb'
require 'google/rpc/status_pb'
require 'google/type/latlng_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.cloud.dialogflow.v2beta1.DetectIntentRequest" do
    optional :session, :string, 1
    optional :query_params, :message, 2, "google.cloud.dialogflow.v2beta1.QueryParameters"
    optional :query_input, :message, 3, "google.cloud.dialogflow.v2beta1.QueryInput"
    optional :input_audio, :bytes, 5
  end
  add_message "google.cloud.dialogflow.v2beta1.DetectIntentResponse" do
    optional :response_id, :string, 1
    optional :query_result, :message, 2, "google.cloud.dialogflow.v2beta1.QueryResult"
    optional :webhook_status, :message, 3, "google.rpc.Status"
  end
  add_message "google.cloud.dialogflow.v2beta1.QueryParameters" do
    optional :time_zone, :string, 1
    optional :geo_location, :message, 2, "google.type.LatLng"
    repeated :contexts, :message, 3, "google.cloud.dialogflow.v2beta1.Context"
    optional :reset_contexts, :bool, 4
    repeated :session_entity_types, :message, 5, "google.cloud.dialogflow.v2beta1.SessionEntityType"
    optional :payload, :message, 6, "google.protobuf.Struct"
  end
  add_message "google.cloud.dialogflow.v2beta1.QueryInput" do
    oneof :input do
      optional :audio_config, :message, 1, "google.cloud.dialogflow.v2beta1.InputAudioConfig"
      optional :text, :message, 2, "google.cloud.dialogflow.v2beta1.TextInput"
      optional :event, :message, 3, "google.cloud.dialogflow.v2beta1.EventInput"
    end
  end
  add_message "google.cloud.dialogflow.v2beta1.QueryResult" do
    optional :query_text, :string, 1
    optional :language_code, :string, 15
    optional :speech_recognition_confidence, :float, 2
    optional :action, :string, 3
    optional :parameters, :message, 4, "google.protobuf.Struct"
    optional :all_required_params_present, :bool, 5
    optional :fulfillment_text, :string, 6
    repeated :fulfillment_messages, :message, 7, "google.cloud.dialogflow.v2beta1.Intent.Message"
    optional :webhook_source, :string, 8
    optional :webhook_payload, :message, 9, "google.protobuf.Struct"
    repeated :output_contexts, :message, 10, "google.cloud.dialogflow.v2beta1.Context"
    optional :intent, :message, 11, "google.cloud.dialogflow.v2beta1.Intent"
    optional :intent_detection_confidence, :float, 12
    optional :diagnostic_info, :message, 14, "google.protobuf.Struct"
  end
  add_message "google.cloud.dialogflow.v2beta1.StreamingDetectIntentRequest" do
    optional :session, :string, 1
    optional :query_params, :message, 2, "google.cloud.dialogflow.v2beta1.QueryParameters"
    optional :query_input, :message, 3, "google.cloud.dialogflow.v2beta1.QueryInput"
    optional :single_utterance, :bool, 4
    optional :input_audio, :bytes, 6
  end
  add_message "google.cloud.dialogflow.v2beta1.StreamingDetectIntentResponse" do
    optional :response_id, :string, 1
    optional :recognition_result, :message, 2, "google.cloud.dialogflow.v2beta1.StreamingRecognitionResult"
    optional :query_result, :message, 3, "google.cloud.dialogflow.v2beta1.QueryResult"
    optional :webhook_status, :message, 4, "google.rpc.Status"
  end
  add_message "google.cloud.dialogflow.v2beta1.StreamingRecognitionResult" do
    optional :message_type, :enum, 1, "google.cloud.dialogflow.v2beta1.StreamingRecognitionResult.MessageType"
    optional :transcript, :string, 2
    optional :is_final, :bool, 3
    optional :confidence, :float, 4
  end
  add_enum "google.cloud.dialogflow.v2beta1.StreamingRecognitionResult.MessageType" do
    value :MESSAGE_TYPE_UNSPECIFIED, 0
    value :TRANSCRIPT, 1
    value :END_OF_SINGLE_UTTERANCE, 2
  end
  add_message "google.cloud.dialogflow.v2beta1.InputAudioConfig" do
    optional :audio_encoding, :enum, 1, "google.cloud.dialogflow.v2beta1.AudioEncoding"
    optional :sample_rate_hertz, :int32, 2
    optional :language_code, :string, 3
    repeated :phrase_hints, :string, 4
  end
  add_message "google.cloud.dialogflow.v2beta1.TextInput" do
    optional :text, :string, 1
    optional :language_code, :string, 2
  end
  add_message "google.cloud.dialogflow.v2beta1.EventInput" do
    optional :name, :string, 1
    optional :parameters, :message, 2, "google.protobuf.Struct"
    optional :language_code, :string, 3
  end
  add_enum "google.cloud.dialogflow.v2beta1.AudioEncoding" do
    value :AUDIO_ENCODING_UNSPECIFIED, 0
    value :AUDIO_ENCODING_LINEAR_16, 1
    value :AUDIO_ENCODING_FLAC, 2
    value :AUDIO_ENCODING_MULAW, 3
    value :AUDIO_ENCODING_AMR, 4
    value :AUDIO_ENCODING_AMR_WB, 5
    value :AUDIO_ENCODING_OGG_OPUS, 6
    value :AUDIO_ENCODING_SPEEX_WITH_HEADER_BYTE, 7
  end
end

module Google
  module Cloud
    module Dialogflow
      module V2beta1
        DetectIntentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.DetectIntentRequest").msgclass
        DetectIntentResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.DetectIntentResponse").msgclass
        QueryParameters = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.QueryParameters").msgclass
        QueryInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.QueryInput").msgclass
        QueryResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.QueryResult").msgclass
        StreamingDetectIntentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.StreamingDetectIntentRequest").msgclass
        StreamingDetectIntentResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.StreamingDetectIntentResponse").msgclass
        StreamingRecognitionResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.StreamingRecognitionResult").msgclass
        StreamingRecognitionResult::MessageType = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.StreamingRecognitionResult.MessageType").enummodule
        InputAudioConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.InputAudioConfig").msgclass
        TextInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.TextInput").msgclass
        EventInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.EventInput").msgclass
        AudioEncoding = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2beta1.AudioEncoding").enummodule
      end
    end
  end
end
